/*
 * Copyright 2026 Jonas Kaninda
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

package routes

import (
	"net/http"

	"github.com/goposta/posta/internal/dto"
	"github.com/goposta/posta/internal/handlers"
	"github.com/goposta/posta/internal/models"
	"github.com/goposta/posta/internal/services/email"
	"github.com/jkaninda/okapi"
)

func (r *Router) workspaceResourceRoutes() []okapi.RouteDefinition {
	opsGroup := r.v1.Group("/workspaces/current", r.mw.jwtAuth.Middleware, r.mw.workspace).WithTagInfo(okapi.GroupTag{
		Name:        "Workspace resources",
		Description: "Operational resources scoped to the active workspace: sending, templates, stylesheets, languages, API keys, contacts, subscribers, campaigns, domains, SMTP servers, webhooks, suppressions, and workspace analytics.",
	})
	opsGroup.WithBearerAuth()

	routes := []okapi.RouteDefinition{
		{
			Method:      http.MethodGet,
			Path:        "/dashboard/stats",
			Handler:     r.h.dashboard.Stats,
			Group:       opsGroup,
			Summary:     "Get dashboard statistics",
			Description: "Returns email sending statistics for the authenticated user",
			Response:    &dto.Response[handlers.DashboardStats]{},
		},
		{
			Method:      http.MethodGet,
			Path:        "/analytics",
			Handler:     okapi.H(r.h.analytics.UserAnalytics),
			Group:       opsGroup,
			Summary:     "Email analytics",
			Description: "Returns daily email counts and status breakdown for the authenticated user",
			Request:     &handlers.AnalyticsRequest{},
			Response:    &dto.Response[handlers.AnalyticsResponse]{},
		},
		{
			Method:      http.MethodGet,
			Path:        "/analytics/dashboard",
			Handler:     okapi.H(r.h.analytics.UserDashboardAnalytics),
			Group:       opsGroup,
			Summary:     "Dashboard analytics",
			Description: "Returns delivery rate trends, bounce rate graphs, and latency percentiles",
			Request:     &handlers.DashboardAnalyticsRequest{},
			Response:    &dto.Response[handlers.DashboardAnalyticsResponse]{},
		},
		{
			Method:      http.MethodGet,
			Path:        "/analytics/providers",
			Handler:     okapi.H(r.h.analytics.UserProviderBreakdown),
			Group:       opsGroup,
			Summary:     "Deliverability by provider",
			Description: "Returns sent/failed counts and delivery rate grouped by recipient mailbox provider (Gmail, Outlook, Yahoo, ...)",
			Request:     &handlers.ProviderBreakdownRequest{},
			Response:    &dto.Response[handlers.ProviderBreakdownResponse]{},
		},
		{
			Method:      http.MethodGet,
			Path:        "/emails",
			Handler:     okapi.H(r.h.email.List),
			Group:       opsGroup,
			Summary:     "List emails",
			Description: "List sent emails with pagination",
			Request:     &handlers.ListRequest{},
			Response:    &dto.PageableResponse[models.Email]{},
		},
		{
			Method:   http.MethodGet,
			Path:     "/emails/{id}",
			Handler:  okapi.H(r.h.email.Get),
			Group:    opsGroup,
			Summary:  "Get email details",
			Response: &dto.Response[models.Email]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "string", "Email UUID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:      http.MethodGet,
			Path:        "/emails/{id}/status",
			Handler:     okapi.H(r.h.email.GetStatus),
			Group:       opsGroup,
			Summary:     "Get email delivery status",
			Description: "Returns a lightweight status view for polling email delivery progress. Only the email owner can access this.",
			Response:    &dto.Response[handlers.EmailStatusResponse]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "string", "Email UUID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:      http.MethodPost,
			Path:        "/emails/{id}/retry",
			Handler:     okapi.H(r.h.email.Retry),
			Group:       opsGroup,
			Summary:     "Retry failed email",
			Description: "Re-enqueue a failed email for another delivery attempt",
			Response:    &dto.Response[email.SendResponse]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "string", "Email UUID"),
				okapi.DocErrorResponse(400, &dto.ErrorResponseBody{}),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:      http.MethodPost,
			Path:        "/emails/preview",
			Handler:     okapi.H(r.h.email.Preview),
			Group:       opsGroup,
			Summary:     "Preview email from template",
			Description: "Render a template with variables and return the HTML, text, and subject without sending.",
			Request:     &handlers.PreviewEmailRequest{},
			Response:    &dto.Response[handlers.PreviewEmailResponse]{},
			Options: []okapi.RouteOption{
				okapi.DocErrorResponse(400, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:      http.MethodPost,
			Path:        "/api-keys",
			Handler:     okapi.H(r.h.apiKey.Create),
			Group:       opsGroup,
			Middlewares: []okapi.Middleware{r.mw.verifiedEmail},
			Summary:     "Create API key",
			Description: "Generate a new API key. The raw key is only shown once in the response.",
			Request:     &handlers.CreateAPIKeyRequest{},
			Options: []okapi.RouteOption{
				okapi.DocResponse(201, &dto.Response[dto.APIKeyCreatedData]{}),
				okapi.DocErrorResponse(403, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:   http.MethodGet,
			Path:     "/api-keys",
			Handler:  okapi.H(r.h.apiKey.List),
			Group:    opsGroup,
			Summary:  "List API keys",
			Request:  &handlers.ListRequest{},
			Response: &dto.PageableResponse[models.APIKey]{},
		},
		{
			Method:   http.MethodPut,
			Path:     "/api-keys/{id:int}/revoke",
			Handler:  okapi.H(r.h.apiKey.Revoke),
			Group:    opsGroup,
			Summary:  "Revoke API key",
			Response: &dto.Response[dto.MessageData]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "API key ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:   http.MethodDelete,
			Path:     "/api-keys/{id:int}",
			Handler:  okapi.H(r.h.apiKey.Delete),
			Group:    opsGroup,
			Summary:  "Delete API key",
			Response: &dto.Response[dto.MessageData]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "API key ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:  http.MethodPost,
			Path:    "/templates",
			Handler: okapi.H(r.h.template.Create),
			Group:   opsGroup,
			Tags:    []string{"User"},
			Summary: "Create template",
			Request: &handlers.CreateTemplateRequest{},
			Options: []okapi.RouteOption{
				okapi.DocResponse(201, &dto.Response[models.Template]{}),
				okapi.DocErrorResponse(409, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:   http.MethodGet,
			Path:     "/templates",
			Handler:  okapi.H(r.h.template.List),
			Group:    opsGroup,
			Summary:  "List templates",
			Request:  &handlers.ListTemplatesRequest{},
			Response: &dto.PageableResponse[models.Template]{},
		},
		{
			Method:   http.MethodPut,
			Path:     "/templates/{id:int}",
			Handler:  okapi.H(r.h.template.Update),
			Group:    opsGroup,
			Summary:  "Update template",
			Request:  &handlers.UpdateTemplateRequest{},
			Response: &dto.Response[models.Template]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Template ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:  http.MethodDelete,
			Path:    "/templates/{id:int}",
			Handler: okapi.H(r.h.template.Delete),
			Group:   opsGroup,
			Tags:    []string{"User"},
			Summary: "Delete template",
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Template ID"),
				okapi.DocResponse(204, nil),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:      http.MethodPost,
			Path:        "/templates/preview",
			Handler:     okapi.H(r.h.template.Preview),
			Group:       opsGroup,
			Summary:     "Preview template",
			Description: "Render a template with sample data and return the result",
			Request:     &handlers.PreviewTemplateRequest{},
			Response:    &dto.Response[handlers.PreviewResult]{},
		},
		{
			Method:      http.MethodPost,
			Path:        "/templates/{id:int}/send-test",
			Handler:     okapi.H(r.h.template.SendTest),
			Group:       opsGroup,
			Summary:     "Send test email",
			Description: "Send a test email using a template with sample data",
			Request:     &handlers.SendTestRequest{},
			Response:    &dto.Response[email.SendResponse]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Template ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:      http.MethodGet,
			Path:        "/templates/{id:int}/export",
			Handler:     okapi.H(r.h.template.Export),
			Group:       opsGroup,
			Summary:     "Export template",
			Description: "Export a template with all versions and localizations as JSON",
			Response:    &dto.Response[handlers.TemplateExport]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Template ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:      http.MethodPost,
			Path:        "/templates/import",
			Handler:     okapi.H(r.h.template.Import),
			Group:       opsGroup,
			Summary:     "Import template",
			Description: "Import a template from a previously exported JSON payload",
			Request:     &handlers.ImportTemplateRequest{},
			Options: []okapi.RouteOption{
				okapi.DocResponse(201, &dto.Response[models.Template]{}),
				okapi.DocErrorResponse(409, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:      http.MethodPost,
			Path:        "/templates/import-html",
			Handler:     r.h.template.ImportHTML,
			Group:       opsGroup,
			Tags:        []string{"Templates"},
			Summary:     "Import HTML template",
			Description: "Upload an .html file to create a template. CSS from <style> blocks is extracted into a separate stylesheet.",
			Options: []okapi.RouteOption{
				okapi.DocResponse(201, &dto.Response[models.Template]{}),
				okapi.DocErrorResponse(409, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:   http.MethodGet,
			Path:     "/templates/{id:int}/versions",
			Handler:  okapi.H(r.h.version.List),
			Group:    opsGroup,
			Tags:     []string{"Template Versions"},
			Summary:  "List template versions",
			Response: &dto.Response[[]models.TemplateVersion]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Template ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:  http.MethodPost,
			Path:    "/templates/{id:int}/versions",
			Handler: okapi.H(r.h.version.Create),
			Group:   opsGroup,
			Tags:    []string{"Template Versions"},
			Summary: "Create template version",
			Request: &handlers.CreateVersionRequest{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Template ID"),
				okapi.DocResponse(201, &dto.Response[models.TemplateVersion]{}),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:   http.MethodPut,
			Path:     "/templates/{id:int}/versions/{versionId:int}",
			Handler:  okapi.H(r.h.version.Update),
			Group:    opsGroup,
			Tags:     []string{"Template Versions"},
			Summary:  "Update template version",
			Request:  &handlers.UpdateVersionRequest{},
			Response: &dto.Response[models.TemplateVersion]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Template ID"),
				okapi.DocPathParam("versionId", "integer", "Version ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:   http.MethodPost,
			Path:     "/templates/{id:int}/activate/{versionId:int}",
			Handler:  okapi.H(r.h.version.Activate),
			Group:    opsGroup,
			Tags:     []string{"Template Versions"},
			Summary:  "Activate template version",
			Response: &dto.Response[models.Template]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Template ID"),
				okapi.DocPathParam("versionId", "integer", "Version ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:  http.MethodDelete,
			Path:    "/templates/{id:int}/versions/{versionId:int}",
			Handler: okapi.H(r.h.version.Delete),
			Group:   opsGroup,
			Tags:    []string{"Template Versions"},
			Summary: "Delete template version",
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Template ID"),
				okapi.DocPathParam("versionId", "integer", "Version ID"),
				okapi.DocResponse(204, nil),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:   http.MethodGet,
			Path:     "/templates/{id:int}/versions/{versionId:int}/localizations",
			Handler:  okapi.H(r.h.localization.List),
			Group:    opsGroup,
			Tags:     []string{"Template Localizations"},
			Summary:  "List localizations for a version",
			Response: &dto.Response[[]models.TemplateLocalization]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Template ID"),
				okapi.DocPathParam("versionId", "integer", "Version ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:  http.MethodPost,
			Path:    "/templates/{id:int}/versions/{versionId:int}/localizations",
			Handler: okapi.H(r.h.localization.Create),
			Group:   opsGroup,
			Tags:    []string{"Template Localizations"},
			Summary: "Create localization",
			Request: &handlers.CreateLocalizationRequest{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Template ID"),
				okapi.DocPathParam("versionId", "integer", "Version ID"),
				okapi.DocResponse(201, &dto.Response[models.TemplateLocalization]{}),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
				okapi.DocErrorResponse(409, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:   http.MethodPut,
			Path:     "/localizations/{localizationId:int}",
			Handler:  okapi.H(r.h.localization.Update),
			Group:    opsGroup,
			Tags:     []string{"Template Localizations"},
			Summary:  "Update localization",
			Request:  &handlers.UpdateLocalizationRequest{},
			Response: &dto.Response[models.TemplateLocalization]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("localizationId", "integer", "Localization ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:  http.MethodDelete,
			Path:    "/localizations/{localizationId:int}",
			Handler: okapi.H(r.h.localization.Delete),
			Group:   opsGroup,
			Tags:    []string{"Template Localizations"},
			Summary: "Delete localization",
			Options: []okapi.RouteOption{
				okapi.DocPathParam("localizationId", "integer", "Localization ID"),
				okapi.DocResponse(204, nil),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:      http.MethodPost,
			Path:        "/templates/{id:int}/versions/{versionId:int}/preview",
			Handler:     okapi.H(r.h.localization.Preview),
			Group:       opsGroup,
			Tags:        []string{"Template Localizations"},
			Summary:     "Preview localized template",
			Description: "Render a specific language version of a template with sample data",
			Request:     &handlers.PreviewLocalizationRequest{},
			Response:    &dto.Response[handlers.PreviewResult]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Template ID"),
				okapi.DocPathParam("versionId", "integer", "Version ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:  http.MethodPost,
			Path:    "/languages",
			Handler: okapi.H(r.h.language.Create),
			Group:   opsGroup,
			Tags:    []string{"Languages"},
			Summary: "Create language",
			Request: &handlers.CreateLanguageRequest{},
			Options: []okapi.RouteOption{
				okapi.DocResponse(201, &dto.Response[models.Language]{}),
				okapi.DocErrorResponse(409, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:   http.MethodGet,
			Path:     "/languages",
			Handler:  okapi.H(r.h.language.List),
			Group:    opsGroup,
			Tags:     []string{"Languages"},
			Summary:  "List languages",
			Request:  &handlers.ListRequest{},
			Response: &dto.PageableResponse[models.Language]{},
		},
		{
			Method:   http.MethodPut,
			Path:     "/languages/{id:int}",
			Handler:  okapi.H(r.h.language.Update),
			Group:    opsGroup,
			Tags:     []string{"Languages"},
			Summary:  "Update language",
			Request:  &handlers.UpdateLanguageRequest{},
			Response: &dto.Response[models.Language]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Language ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:  http.MethodDelete,
			Path:    "/languages/{id:int}",
			Handler: okapi.H(r.h.language.Delete),
			Group:   opsGroup,
			Tags:    []string{"Languages"},
			Summary: "Delete language",
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Language ID"),
				okapi.DocResponse(204, nil),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:  http.MethodPost,
			Path:    "/stylesheets",
			Handler: okapi.H(r.h.stylesheet.Create),
			Group:   opsGroup,
			Tags:    []string{"User"},
			Summary: "Create stylesheet",
			Request: &handlers.CreateStyleSheetRequest{},
			Options: []okapi.RouteOption{
				okapi.DocResponse(201, &dto.Response[models.StyleSheet]{}),
				okapi.DocErrorResponse(409, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:   http.MethodGet,
			Path:     "/stylesheets",
			Handler:  okapi.H(r.h.stylesheet.List),
			Group:    opsGroup,
			Summary:  "List stylesheets",
			Request:  &handlers.ListRequest{},
			Response: &dto.PageableResponse[models.StyleSheet]{},
		},
		{
			Method:   http.MethodPut,
			Path:     "/stylesheets/{id:int}",
			Handler:  okapi.H(r.h.stylesheet.Update),
			Group:    opsGroup,
			Summary:  "Update stylesheet",
			Request:  &handlers.UpdateStyleSheetRequest{},
			Response: &dto.Response[models.StyleSheet]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "StyleSheet ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:  http.MethodDelete,
			Path:    "/stylesheets/{id:int}",
			Handler: okapi.H(r.h.stylesheet.Delete),
			Group:   opsGroup,
			Tags:    []string{"User"},
			Summary: "Delete stylesheet",
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "StyleSheet ID"),
				okapi.DocResponse(204, nil),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:  http.MethodPost,
			Path:    "/smtp-servers",
			Handler: okapi.H(r.h.smtp.Create),
			Group:   opsGroup,
			Tags:    []string{"User"},
			Summary: "Add SMTP server",
			Request: &handlers.CreateSMTPRequest{},
			Options: []okapi.RouteOption{
				okapi.DocResponse(201, &dto.Response[models.SMTPServer]{}),
			},
		},
		{
			Method:   http.MethodGet,
			Path:     "/smtp-servers",
			Handler:  okapi.H(r.h.smtp.List),
			Group:    opsGroup,
			Summary:  "List SMTP servers",
			Request:  &handlers.ListRequest{},
			Response: &dto.PageableResponse[models.SMTPServer]{},
		},
		{
			Method:   http.MethodGet,
			Path:     "/smtp-servers/{id:int}",
			Handler:  okapi.H(r.h.smtp.Get),
			Group:    opsGroup,
			Summary:  "Get SMTP server",
			Request:  &handlers.GetSMTPRequest{},
			Response: &dto.Response[models.SMTPServer]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "SMTP server ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:   http.MethodPut,
			Path:     "/smtp-servers/{id:int}",
			Handler:  okapi.H(r.h.smtp.Update),
			Group:    opsGroup,
			Summary:  "Update SMTP server",
			Request:  &handlers.UpdateSMTPRequest{},
			Response: &dto.Response[models.SMTPServer]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "SMTP server ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:  http.MethodDelete,
			Path:    "/smtp-servers/{id:int}",
			Handler: okapi.H(r.h.smtp.Delete),
			Group:   opsGroup,
			Tags:    []string{"User"},
			Summary: "Delete SMTP server",
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "SMTP server ID"),
				okapi.DocResponse(204, nil),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:   http.MethodPost,
			Path:     "/smtp-servers/{id:int}/test",
			Handler:  okapi.H(r.h.smtp.Test),
			Group:    opsGroup,
			Summary:  "Test SMTP server connection",
			Response: &dto.Response[dto.MessageData]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "SMTP server ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:  http.MethodPost,
			Path:    "/webhooks",
			Handler: okapi.H(r.h.webhook.Create),
			Group:   opsGroup,
			Tags:    []string{"User"},
			Summary: "Create webhook",
			Request: &handlers.CreateWebhookRequest{},
			Options: []okapi.RouteOption{
				okapi.DocResponse(201, &dto.Response[models.Webhook]{}),
			},
		},
		{
			Method:   http.MethodGet,
			Path:     "/webhooks",
			Handler:  okapi.H(r.h.webhook.List),
			Group:    opsGroup,
			Summary:  "List webhooks",
			Request:  &handlers.ListRequest{},
			Response: &dto.PageableResponse[models.Webhook]{},
		},
		{
			Method:  http.MethodDelete,
			Path:    "/webhooks/{id:int}",
			Handler: okapi.H(r.h.webhook.Delete),
			Group:   opsGroup,
			Tags:    []string{"User"},
			Summary: "Delete webhook",
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Webhook ID"),
				okapi.DocResponse(204, nil),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:   http.MethodGet,
			Path:     "/webhook-deliveries",
			Handler:  okapi.H(r.h.webhookDelivery.List),
			Group:    opsGroup,
			Summary:  "List webhook deliveries",
			Request:  &handlers.ListRequest{},
			Response: &dto.PageableResponse[models.WebhookDelivery]{},
		},
		{
			Method:      http.MethodPost,
			Path:        "/domains",
			Handler:     okapi.H(r.h.domain.Create),
			Group:       opsGroup,
			Summary:     "Add domain",
			Description: "Register a domain for verification. Returns the DNS records that must be configured.",
			Request:     &handlers.CreateDomainRequest{},
			Options: []okapi.RouteOption{
				okapi.DocResponse(201, &dto.Response[handlers.DomainWithRecords]{}),
				okapi.DocErrorResponse(409, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:   http.MethodGet,
			Path:     "/domains",
			Handler:  okapi.H(r.h.domain.List),
			Group:    opsGroup,
			Summary:  "List domains",
			Request:  &handlers.ListRequest{},
			Response: &dto.PageableResponse[models.Domain]{},
		},
		{
			Method:   http.MethodGet,
			Path:     "/domains/{id:int}",
			Handler:  okapi.H(r.h.domain.Get),
			Group:    opsGroup,
			Summary:  "Get domain details",
			Response: &dto.Response[handlers.DomainWithRecords]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Domain ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:  http.MethodDelete,
			Path:    "/domains/{id:int}",
			Handler: okapi.H(r.h.domain.Delete),
			Group:   opsGroup,
			Tags:    []string{"User"},
			Summary: "Delete domain",
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Domain ID"),
				okapi.DocResponse(204, nil),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:      http.MethodPost,
			Path:        "/domains/{id:int}/verify",
			Handler:     okapi.H(r.h.domain.Verify),
			Group:       opsGroup,
			Summary:     "Verify domain DNS records",
			Description: "Check DNS records (SPF, DKIM, DMARC) for the domain",
			Response:    &dto.Response[any]{},
			Options: []okapi.RouteOption{
				okapi.DocPathParam("id", "integer", "Domain ID"),
				okapi.DocErrorResponse(404, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:      http.MethodPost,
			Path:        "/bounces",
			Handler:     okapi.H(r.h.bounce.Record),
			Group:       opsGroup,
			Summary:     "Record a bounce",
			Description: "Record a bounce or complaint. Hard bounces and complaints auto-suppress the recipient.",
			Request:     &handlers.RecordBounceRequest{},
			Options: []okapi.RouteOption{
				okapi.DocResponse(201, &dto.Response[models.Bounce]{}),
			},
		},
		{
			Method:   http.MethodGet,
			Path:     "/bounces",
			Handler:  okapi.H(r.h.bounce.List),
			Group:    opsGroup,
			Summary:  "List bounces",
			Request:  &handlers.ListRequest{},
			Response: &dto.PageableResponse[models.Bounce]{},
		},
		{
			Method:  http.MethodPost,
			Path:    "/suppressions",
			Handler: okapi.H(r.h.suppression.Create),
			Group:   opsGroup,
			Tags:    []string{"User"},
			Summary: "Add to suppression list",
			Request: &handlers.CreateSuppressionRequest{},
			Options: []okapi.RouteOption{
				okapi.DocResponse(201, &dto.Response[models.Suppression]{}),
				okapi.DocErrorResponse(409, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:   http.MethodGet,
			Path:     "/suppressions",
			Handler:  okapi.H(r.h.suppression.List),
			Group:    opsGroup,
			Summary:  "List suppressed emails",
			Request:  &handlers.ListSuppressionsRequest{},
			Response: &dto.PageableResponse[models.Suppression]{},
		},
		{
			Method:  http.MethodDelete,
			Path:    "/suppressions",
			Handler: okapi.H(r.h.suppression.Delete),
			Group:   opsGroup,
			Tags:    []string{"User"},
			Summary: "Remove from suppression list",
			Request: &handlers.DeleteSuppressionRequest{},
			Options: []okapi.RouteOption{
				okapi.DocResponse(204, nil),
			},
		},
		{
			Method:  http.MethodPost,
			Path:    "/unsubscribe-lists",
			Handler: okapi.H(r.h.unsubscribeList.Create),
			Group:   opsGroup,
			Tags:    []string{"Unsubscribe Lists"},
			Summary: "Create unsubscribe list",
			Request: &handlers.CreateUnsubscribeListRequest{},
			Options: []okapi.RouteOption{
				okapi.DocResponse(201, &dto.Response[models.UnsubscribeList]{}),
				okapi.DocErrorResponse(409, &dto.ErrorResponseBody{}),
			},
		},
		{
			Method:   http.MethodGet,
			Path:     "/unsubscribe-lists",
			Handler:  okapi.H(r.h.unsubscribeList.List),
			Group:    opsGroup,
			Tags:     []string{"Unsubscribe Lists"},
			Summary:  "List unsubscribe lists",
			Request:  &handlers.ListRequest{},
			Response: &dto.PageableResponse[models.UnsubscribeList]{},
		},
		{
			Method:   http.MethodGet,
			Path:     "/unsubscribe-lists/{id:int}",
			Handler:  okapi.H(r.h.unsubscribeList.Get),
			Group:    opsGroup,
			Tags:     []string{"Unsubscribe Lists"},
			Summary:  "Get unsubscribe list",
			Response: &dto.Response[models.UnsubscribeList]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "List ID")},
		},
		{
			Method:   http.MethodPut,
			Path:     "/unsubscribe-lists/{id:int}",
			Handler:  okapi.H(r.h.unsubscribeList.Update),
			Group:    opsGroup,
			Tags:     []string{"Unsubscribe Lists"},
			Summary:  "Update unsubscribe list",
			Request:  &handlers.UpdateUnsubscribeListRequest{},
			Response: &dto.Response[models.UnsubscribeList]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "List ID")},
		},
		{
			Method:  http.MethodDelete,
			Path:    "/unsubscribe-lists/{id:int}",
			Handler: okapi.H(r.h.unsubscribeList.Delete),
			Group:   opsGroup,
			Tags:    []string{"Unsubscribe Lists"},
			Summary: "Delete unsubscribe list",
			Options: []okapi.RouteOption{okapi.DocPathParam("id", "integer", "List ID"), okapi.DocResponse(204, nil)},
		},
		{
			Method:      http.MethodGet,
			Path:        "/contacts",
			Handler:     okapi.H(r.h.contact.List),
			Group:       opsGroup,
			Summary:     "List contacts",
			Description: "List all recipient email addresses with sent/failed counts. Use the search query parameter to filter by email or name.",
			Request:     &handlers.ListContactsRequest{},
			Response:    &dto.PageableResponse[models.Contact]{},
		},
		{
			Method:      http.MethodGet,
			Path:        "/contacts/{id:int}",
			Handler:     okapi.H(r.h.contact.Get),
			Group:       opsGroup,
			Summary:     "Get contact details",
			Description: "Get a single contact by ID with suppression status",
			Request:     &handlers.GetByIDRequest{},
			Response:    &dto.Response[models.Contact]{},
		},
		{
			Method:  http.MethodPost,
			Path:    "/subscribers",
			Handler: okapi.H(r.h.subscriber.Create),
			Group:   opsGroup,
			Tags:    []string{"Subscribers"},
			Summary: "Create subscriber",
			Request: &handlers.CreateSubscriberRequest{},
			Options: []okapi.RouteOption{okapi.DocResponse(201, &dto.Response[models.Subscriber]{})},
		},
		{
			Method:   http.MethodGet,
			Path:     "/subscribers",
			Handler:  okapi.H(r.h.subscriber.List),
			Group:    opsGroup,
			Tags:     []string{"Subscribers"},
			Summary:  "List subscribers",
			Request:  &handlers.ListSubscribersRequest{},
			Response: &dto.PageableResponse[models.Subscriber]{},
		},
		{
			Method:   http.MethodGet,
			Path:     "/subscribers/{id:int}",
			Handler:  okapi.H(r.h.subscriber.Get),
			Group:    opsGroup,
			Tags:     []string{"Subscribers"},
			Summary:  "Get subscriber",
			Response: &dto.Response[models.Subscriber]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "Subscriber ID")},
		},
		{
			Method:   http.MethodPut,
			Path:     "/subscribers/{id:int}",
			Handler:  okapi.H(r.h.subscriber.Update),
			Group:    opsGroup,
			Tags:     []string{"Subscribers"},
			Summary:  "Update subscriber",
			Request:  &handlers.UpdateSubscriberRequest{},
			Response: &dto.Response[models.Subscriber]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "Subscriber ID")},
		},
		{
			Method:  http.MethodDelete,
			Path:    "/subscribers/{id:int}",
			Handler: okapi.H(r.h.subscriber.Delete),
			Group:   opsGroup,
			Tags:    []string{"Subscribers"},
			Summary: "Delete subscriber",
			Options: []okapi.RouteOption{okapi.DocPathParam("id", "integer", "Subscriber ID"), okapi.DocResponse(204, nil)},
		},
		{
			Method:   http.MethodPost,
			Path:     "/subscribers/import/json",
			Handler:  okapi.H(r.h.subscriber.BulkImportJSON),
			Group:    opsGroup,
			Tags:     []string{"Subscribers"},
			Summary:  "Bulk import subscribers (JSON)",
			Request:  &handlers.BulkImportSubscribersRequest{},
			Response: &dto.Response[handlers.BulkImportResult]{},
		},
		{
			Method:      http.MethodPost,
			Path:        "/subscribers/import/csv",
			Handler:     r.h.subscriber.BulkImportCSV,
			Group:       opsGroup,
			Tags:        []string{"Subscribers"},
			Summary:     "Bulk import subscribers (CSV)",
			Description: "Upload a CSV file with optional column_mapping JSON field",
			Response:    &dto.Response[handlers.BulkImportResult]{},
		},
		{
			Method:  http.MethodPost,
			Path:    "/subscriber-lists",
			Handler: okapi.H(r.h.subscriberList.Create),
			Group:   opsGroup,
			Tags:    []string{"Subscriber Lists"},
			Summary: "Create subscriber list",
			Request: &handlers.CreateSubscriberListRequest{},
			Options: []okapi.RouteOption{okapi.DocResponse(201, &dto.Response[models.SubscriberList]{})},
		},
		{
			Method:   http.MethodGet,
			Path:     "/subscriber-lists",
			Handler:  okapi.H(r.h.subscriberList.List),
			Group:    opsGroup,
			Tags:     []string{"Subscriber Lists"},
			Summary:  "List subscriber lists",
			Request:  &handlers.ListRequest{},
			Response: &dto.PageableResponse[handlers.SubscriberListWithCount]{},
		},
		{
			Method:   http.MethodGet,
			Path:     "/subscriber-lists/{id:int}",
			Handler:  okapi.H(r.h.subscriberList.Get),
			Group:    opsGroup,
			Tags:     []string{"Subscriber Lists"},
			Summary:  "Get subscriber list",
			Response: &dto.Response[handlers.SubscriberListWithCount]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "List ID")},
		},
		{
			Method:   http.MethodPut,
			Path:     "/subscriber-lists/{id:int}",
			Handler:  okapi.H(r.h.subscriberList.Update),
			Group:    opsGroup,
			Tags:     []string{"Subscriber Lists"},
			Summary:  "Update subscriber list",
			Request:  &handlers.UpdateSubscriberListRequest{},
			Response: &dto.Response[models.SubscriberList]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "List ID")},
		},
		{
			Method:  http.MethodDelete,
			Path:    "/subscriber-lists/{id:int}",
			Handler: okapi.H(r.h.subscriberList.Delete),
			Group:   opsGroup,
			Tags:    []string{"Subscriber Lists"},
			Summary: "Delete subscriber list",
			Options: []okapi.RouteOption{okapi.DocPathParam("id", "integer", "List ID"), okapi.DocResponse(204, nil)},
		},
		{
			Method:   http.MethodPost,
			Path:     "/subscriber-lists/{id:int}/members",
			Handler:  okapi.H(r.h.subscriberList.AddMember),
			Group:    opsGroup,
			Tags:     []string{"Subscriber Lists"},
			Summary:  "Add subscriber to list",
			Request:  &handlers.AddSubscriberToListRequest{},
			Response: &dto.Response[okapi.M]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "List ID")},
		},
		{
			Method:   http.MethodDelete,
			Path:     "/subscriber-lists/{id:int}/members",
			Handler:  okapi.H(r.h.subscriberList.RemoveMember),
			Group:    opsGroup,
			Tags:     []string{"Subscriber Lists"},
			Summary:  "Remove subscriber from list",
			Request:  &handlers.RemoveSubscriberFromListRequest{},
			Response: &dto.Response[okapi.M]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "List ID")},
		},
		{
			Method:   http.MethodGet,
			Path:     "/subscriber-lists/{id:int}/members",
			Handler:  okapi.H(r.h.subscriberList.ListMembers),
			Group:    opsGroup,
			Tags:     []string{"Subscriber Lists"},
			Summary:  "List members of subscriber list",
			Request:  &handlers.ListSubscriberListMembersRequest{},
			Response: &dto.PageableResponse[models.Subscriber]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "List ID")},
		},
		{
			Method:      http.MethodPost,
			Path:        "/subscriber-lists/preview-segment",
			Handler:     okapi.H(r.h.subscriberList.PreviewSegment),
			Group:       opsGroup,
			Tags:        []string{"Subscriber Lists"},
			Summary:     "Preview segment count",
			Description: "Evaluate filter rules and return the number of matching subscribers",
			Request:     &handlers.PreviewSegmentRequest{},
			Response:    &dto.Response[okapi.M]{},
		},
		{
			Method:      http.MethodPost,
			Path:        "/subscriber-lists/{id:int}/unsubscribe",
			Handler:     okapi.H(r.h.subscriberList.UnsubscribeByEmail),
			Group:       opsGroup,
			Tags:        []string{"Subscriber Lists"},
			Summary:     "Unsubscribe an email from a list",
			Description: "API-key-accessible list opt-out. Idempotent. Does not change global subscriber status.",
			Request:     &handlers.ListUnsubscribeByEmailRequest{},
			Response:    &dto.Response[handlers.ListSubscribeResponse]{},
			Options:     []okapi.RouteOption{okapi.DocPathParam("id", "integer", "List ID")},
		},
		{
			Method:      http.MethodPost,
			Path:        "/subscriber-lists/{id:int}/resubscribe",
			Handler:     okapi.H(r.h.subscriberList.ResubscribeByEmail),
			Group:       opsGroup,
			Tags:        []string{"Subscriber Lists"},
			Summary:     "Re-subscribe an email to a list",
			Description: "Reverses a list-scoped opt-out and re-adds to the list (static lists). Idempotent.",
			Request:     &handlers.ListResubscribeByEmailRequest{},
			Response:    &dto.Response[handlers.ListSubscribeResponse]{},
			Options:     []okapi.RouteOption{okapi.DocPathParam("id", "integer", "List ID")},
		},
		{
			Method:  http.MethodPost,
			Path:    "/campaigns",
			Handler: okapi.H(r.h.campaign.Create),
			Group:   opsGroup,
			Tags:    []string{"Campaigns"},
			Summary: "Create campaign",
			Request: &handlers.CreateCampaignRequest{},
			Options: []okapi.RouteOption{okapi.DocResponse(201, &dto.Response[models.Campaign]{})},
		},
		{
			Method:   http.MethodGet,
			Path:     "/campaigns",
			Handler:  okapi.H(r.h.campaign.List),
			Group:    opsGroup,
			Tags:     []string{"Campaigns"},
			Summary:  "List campaigns",
			Request:  &handlers.ListCampaignsRequest{},
			Response: &dto.PageableResponse[handlers.CampaignWithStats]{},
		},
		{
			Method:   http.MethodGet,
			Path:     "/campaigns/{id:int}",
			Handler:  okapi.H(r.h.campaign.Get),
			Group:    opsGroup,
			Tags:     []string{"Campaigns"},
			Summary:  "Get campaign",
			Response: &dto.Response[handlers.CampaignWithStats]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "Campaign ID")},
		},
		{
			Method:   http.MethodPut,
			Path:     "/campaigns/{id:int}",
			Handler:  okapi.H(r.h.campaign.Update),
			Group:    opsGroup,
			Tags:     []string{"Campaigns"},
			Summary:  "Update campaign",
			Request:  &handlers.UpdateCampaignRequest{},
			Response: &dto.Response[models.Campaign]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "Campaign ID")},
		},
		{
			Method:  http.MethodDelete,
			Path:    "/campaigns/{id:int}",
			Handler: okapi.H(r.h.campaign.Delete),
			Group:   opsGroup,
			Tags:    []string{"Campaigns"},
			Summary: "Delete campaign",
			Options: []okapi.RouteOption{okapi.DocPathParam("id", "integer", "Campaign ID"), okapi.DocResponse(204, nil)},
		},
		{
			Method:   http.MethodPost,
			Path:     "/campaigns/{id:int}/send",
			Handler:  okapi.H(r.h.campaign.Send),
			Group:    opsGroup,
			Tags:     []string{"Campaigns"},
			Summary:  "Send campaign",
			Response: &dto.Response[models.Campaign]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "Campaign ID")},
		},
		{
			Method:   http.MethodPost,
			Path:     "/campaigns/{id:int}/pause",
			Handler:  okapi.H(r.h.campaign.Pause),
			Group:    opsGroup,
			Tags:     []string{"Campaigns"},
			Summary:  "Pause campaign",
			Response: &dto.Response[models.Campaign]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "Campaign ID")},
		},
		{
			Method:   http.MethodPost,
			Path:     "/campaigns/{id:int}/resume",
			Handler:  okapi.H(r.h.campaign.Resume),
			Group:    opsGroup,
			Tags:     []string{"Campaigns"},
			Summary:  "Resume campaign",
			Response: &dto.Response[models.Campaign]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "Campaign ID")},
		},
		{
			Method:   http.MethodPost,
			Path:     "/campaigns/{id:int}/cancel",
			Handler:  okapi.H(r.h.campaign.Cancel),
			Group:    opsGroup,
			Tags:     []string{"Campaigns"},
			Summary:  "Cancel campaign",
			Response: &dto.Response[models.Campaign]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "Campaign ID")},
		},
		{
			Method:   http.MethodPost,
			Path:     "/campaigns/{id:int}/duplicate",
			Handler:  okapi.H(r.h.campaign.Duplicate),
			Group:    opsGroup,
			Tags:     []string{"Campaigns"},
			Summary:  "Duplicate campaign",
			Response: &dto.Response[models.Campaign]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "Campaign ID")},
		},
		{
			Method:   http.MethodGet,
			Path:     "/campaigns/{id:int}/messages",
			Handler:  okapi.H(r.h.campaign.ListMessages),
			Group:    opsGroup,
			Tags:     []string{"Campaigns"},
			Summary:  "List campaign messages",
			Request:  &handlers.ListCampaignMessagesRequest{},
			Response: &dto.PageableResponse[models.CampaignMessage]{},
			Options:  []okapi.RouteOption{okapi.DocPathParam("id", "integer", "Campaign ID")},
		},
	}

	return routes
}
